export enum BrowserTo {
  LINKEDIN = 'LINKEDIN',
  GITHUB = 'GITHUB',
  RESUME = 'RESUME',
  CONTACT = 'CONTACT',
  FORTUNE_FRONT = 'FORTUNE_FRONT',
  FORTUNE_BACK = 'FORTUNE_BACK',
  PORTFOLIO = 'PORTFOLIO'
}