export enum ItemType {
    CALCULATOR = 'CALCULATOR',
    SETTINGS = 'SETTINGS',
    TERMINAL = 'TERMINAL',
    RESUME = 'RESUME',
    ABOUT_ME = 'ABOUT ME',
    BROSWER = 'BROSWER',
    CONTACT = 'CONTACT ME'
}