export enum ItemType {
    DEFAULT = 'DEFAULT',
    TRASH = 'TRASH',
    NOTEPAD = 'NOTEPAD',
    FILE_EXPLORER = 'FILE_EXPLORER',
    CALCULATOR = 'CALCULATOR',
    BROWSER = 'BROWSER',
    SETTINGS = 'SETTINGS',
    TERMINAL = 'TERMINAL',
    RESUME= 'RESUME'
}